# USEFUL TO VALIDATE YAML FILE: http://lint.travis-ci.org/

language: android
sudo: false
android:
  components:
    - tools
    - build-tools-25.0.3
    - platform-tools
    - extra-android-m2repository
    - extra-google-android-support

    # The SDK version used to compile your project
    - android-16
    - android-21
    - android-22
    - android-25

jdk: oraclejdk8
os:
  - linux

before_install:
  - chmod +x gradlew

# whitelist
branches:
  only:
    - develop

script:
 #run automated tests
 - ./gradlew test
 # deploy to hockeyapp
 - ./gradlew assembleDebug
 - >
    curl
    -F "status=2"
    -F "notify=1"
    -F "notes=Travis commit: ${TRAVIS_COMMIT_MESSAGE}."
    -F "notes_type=0"
    -F "ipa=@app/build/outputs/apk/app-debug.apk"
    -H "X-HockeyAppToken: ${HOCKEYAPP_TOKEN}"
    https://rink.hockeyapp.net/api/2/apps/upload

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
